Add untested support for authbind to toto init script.

diff --git a/config/server/toto b/config/server/toto
--- a/config/server/toto
+++ b/config/server/toto
@@ -27,12 +27,15 @@ TOTO_JAR=${TOTO_PATH}/toto-standalone.jar
 
 TOTO_USER=mschaef
 
-JVM=/usr/bin/java
+JAVA=/usr/bin/java
 
-JVM_ARGS="-cp ${TOTO_PATH}:${TOTO_JAR} -Ddb.subname=${TOTO_DB_SUBNAME} toto.main"
+JAVA_OPTS="-cp ${TOTO_PATH}:${TOTO_JAR} -Ddb.subname=${TOTO_DB_SUBNAME} toto.main"
 
 PIDFILE=/var/run/toto.pid
 SCRIPTNAME=/etc/init.d/toto
+
+# Uncommend to enable authbind
+# AUTHBIND=yes
 
 # Exit if not root
 if [ `id -u` -ne 0 ]; then
@@ -40,9 +43,9 @@ if [ `id -u` -ne 0 ]; then
         exit 1
 fi
 
-# Exit if the JVM is not installed
-if [ ! -x "$JVM" ]; then
-    echo "The expected JVM was not found at: $JVM"
+# Exit if the JAVA is not installed
+if [ ! -x "$JAVA" ]; then
+    echo "The expected JAVA was not found at: $JAVA"
     exit 1
 fi
 
@@ -55,6 +58,18 @@ fi
 # Read configuration variable file if it is present
 [ -r /etc/default/toto ] && . /etc/default/toto
 
+AUTHBIND_COMMAND=""
+if [ "$AUTHBIND" = "yes" -a "$1" = "start" ]; then
+   JAVA_OPTS="$JAVA_OPTS -Djava.net.preferIPv4Stack=true"
+   AUTHBIND_COMMAND="/usr/bin/authbind --deep /bin/bash -c "
+fi
+
+TOTO_SH="$JAVA $JAVA_OPTS"
+
+if [ "$AUTHBIND" = "yes" -a "$1" = "start" ]; then
+        TOMCAT_SH="'$TOMCAT_SH'"
+fi
+
 # Load the VERBOSE setting and other rcS variables
 . /lib/init/vars.sh
 
@@ -62,6 +77,7 @@ fi
 # Depend on lsb-base (>= 3.2-14) to ensure that this file is present
 # and status_of_proc is working.
 . /lib/lsb/init-functions
+
 
 #
 # Function that starts the daemon/service
@@ -72,11 +88,12 @@ do_start()
 	#   0 if daemon has been started
 	#   1 if daemon was already running
 	#   2 if daemon could not be started
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $JVM --test > /dev/null \
+	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $JAVA --test > /dev/null \
 		|| return 1
 
 	start-stop-daemon --start --quiet --pidfile $PIDFILE \
-                      --make-pidfile --chuid ${TOTO_USER} --background --exec $JVM -- $JVM_ARGS \
+                      --make-pidfile --chuid ${TOTO_USER} --background \
+                      --exec /bin/bash -- -c "$AUTHBIND_COMMAND $TOTO_SH" \
 		|| return 2
 }
 
@@ -90,7 +107,7 @@ do_stop()
 	#   1 if daemon was already stopped
 	#   2 if daemon could not be stopped
 	#   other if a failure occurred
-	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --exec $JVM
+	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
 	RETVAL="$?"
 	[ "$RETVAL" = 2 ] && return 2
 	# Wait for children to finish too if this is a daemon that forks
@@ -99,7 +116,7 @@ do_stop()
 	# that waits for the process to drop all resources that could be
 	# needed by services started subsequently.  A last resort is to
 	# sleep for some time.
-	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $JVM
+	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $JAVA
 	[ "$?" = 2 ] && return 2
 	# Many daemons don't delete their pidfiles when they exit.
 	rm -f $PIDFILE
@@ -137,7 +154,7 @@ case "$1" in
 	esac
 	;;
   status)
-       status_of_proc "$JVM" "toto" && exit 0 || exit $?
+       status_of_proc "$JAVA" "toto" && exit 0 || exit $?
        ;;
   #reload|force-reload)
 	#
